# Generated by Django 4.2.5 on 2023-09-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noutbook',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
